# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
 
trigger:
- main
 
pr: none

pool:
  vmImage: ubuntu-latest


steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
    
- script: |
      npm audit fix --force
      npm install
      ls -la
  displayName: "npm install"
# npm run build --if-present
      # npm run test --if-present

- script: |
    npm run build --if-present
    npm run test --if-present
    ls -la
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Pipeline.Workspace)'
    contents: |
       .
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: node-app
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(Pipeline.Workspace)'
#     artifact: 'node-app'
#     publishLocation: 'pipeline'
